// <auto-generated />
namespace Hospital.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_log : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_log));
        
        string IMigrationMetadata.Id
        {
            get { return "202003311103558_add_log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
